# Streamlit Cloud Secrets
# Add your API key in the Streamlit Cloud dashboard:
# https://share.streamlit.io -> App Settings -> Secrets

# Example format (DO NOT commit actual keys):
# ANTHROPIC_API_KEY = "your-key-here"
